In [1]:
import numpy as np

In [2]:
a = np.array([1.1,2.2,3.3,3.3])
a.dtype

dtype('float64')

In [9]:
a.astype(int).dtype

dtype('int32')

In [19]:
# NumPy 数组生成
# np.ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
    #ndarray通用的同构数据多维容器,其所有的元素必须是相同类型的
    # shape：数组的形状。
    # dtype：数据类型。
    # buffer：对象暴露缓冲区接口。
    # offset：数组数据的偏移量。
    # strides：数据步长。
    # order：{'C'，'F'}，以行或列为主排列顺序。

# numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    # object：列表、元组等。
    # dtype：数据类型。如果未给出，则类型为被保存对象所需的最小类型。
    # copy：布尔类型，默认 True，表示复制对象。
    # order：顺序。
    # subok：布尔类型，表示子类是否被传递。
    # ndmin：生成的数组应具有的最小维数。

arr = np.array([[1,2,3],[4,5,6]],dtype=int)
arr2 = np.array([(1,2),(3,4),(5,6)])

# numpy.arange(start, stop, step, dtype=None)
# python内置函数range的数组版
arr_arange = np.arange(0,10,10,dtype=float)

# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    # start：序列的起始值。
    # stop：序列的结束值。
    # num：生成的样本数。默认值为50。
    # endpoint：布尔值，如果为真，则最后一个样本包含在序列内。
    # retstep：布尔值，如果为真，返回间距。
    # dtype：数组的类型。
arr_line1 = np.linspace(0,10,10,endpoint=True)
arr_line2 = np.linspace(0,10,10,endpoint=False)
print(arr_line1,'\n',arr_line2)

# numpy.ones(shape, dtype=None, order='C')

    # shape：用于指定数组形状，例如（1， 2）或 3。
    # dtype：数据类型。
    # order：{'C'，'F'}，按行或列方式储存数组。

# numpy.zeros(shape, dtype=None, order='C')
# 
#     shape：用于指定数组形状，例如（1， 2）或3。
#     dtype：数据类型。
#     order：{'C'，'F'}，按行或列方式储存数组。

# numpy.eye(N, M=None, k=0, dtype=<type 'float'>)

    # N：输出数组的行数。
    # M：输出数组的列数。
    # k：对角线索引：0（默认）是指主对角线，正值是指上对角线，
# 负值是指下对角线。

# 从已知数据创建
# 
# 我们还可以从已知数据文件、函数中创建 ndarray。NumPy 提供了下面 5 个方法：
# 
#     frombuffer（buffer）：将缓冲区转换为 1 维数组。
#     fromfile（file，dtype，count，sep）：从文本或二进制文件中构建多维数组。
#     fromfunction（function，shape）：通过函数返回值来创建多维数组。
#     fromiter（iterable，dtype，count）：从可迭代对象创建 1 维数组。
#     fromstring（string，dtype，count，sep）：从字符串中创建 1 维数组。

arr_ff = np.fromfunction(lambda a,b: a+b,(5,4))
print(arr_ff)

func = lambda a,b:a+b
print(func(1,2))

# ndarray 数组属性
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

# ndarray.dtype 用来输出数组包含元素的数据类型。
print(array.dtype)

# ndarray.T 用于数组的转置，与 .transpose() 相同。
print(array.T)
print(array.transpose())

# ndarray.imag 用来输出数组包含元素的虚部。
print(array.imag)

# ndarray.real用来输出数组包含元素的实部。
print(array.real)

# ndarray.size用来输出数组中的总包含元素数。
print(array.size)

# ndarray.itemsize输出一个数组元素的字节数。
print(array.itemsize)

# ndarray.nbytes用来输出数组的元素总字节数。
print(array.nbytes)

# ndarray.ndim用来输出数组尺寸。
print(array.ndim)

# ndarray.shape用来输出数组维数组。
print(array.shape)

# ndarray.strides用来遍历数组时，输出每个维度中步进的字节数组。
print(array.strides)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ] 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]
3
int32
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
4
36
2
(3, 3)
(12, 4)


In [28]:
# 数组维度和形状
# 
# 前面，我们已经对 NumPy 数组的类型和常用的生成方法进行了介绍。
# 
# 再继续了解更多内容前，必须先搞清楚一个重要的问题，
# 那就是 NumPy 数组的维度和形状。
# 
# NumPy 数组又被称之为 ndarray 多维数组，那么 n 就可以从 1 维依次递增。

one = np.array([i for i in range(5)])
two = np.array([[i for i in range(5)],[p for p in range(5,10)]])
three = np.array([[[i for i in range(5)],[p for p in range(5)]],
                  [[i for i in range(5)],[p for p in range(5)]]])
print(one.shape,two.shape,three.shape)
print(one.ndim,two.ndim,three.ndim)

(5,) (2, 5) (2, 2, 5)
1 2 3


In [5]:
# 数组基本操作
# 
# 至此，我们了解了如何利用 NumPy 创建各式各样的 ndarray，以及数组形状和维度的概念。
# 接下来，我们将利用学会针对 ndarray 的各种花式操作技巧。

# 重设形状
# reshape 可以在不改变数组数据的同时，
# 改变数组的形状。其中，numpy.reshape() 
# 等效于 ndarray.reshape()。reshape 方法非常简单：
# numpy.reshape(a, newshape)
# 其中，a 表示原数组，newshape 用于指定新的形状(整数或者元组)
# order 表示变换时的读取顺序，默认是按照行依次读取，
# 当 order='F' 时，可以按列依次读取排序。
arr_reshape = np.arange(9).reshape((3,3),order='F')
print(arr_reshape)

# 数组展开
# ravel 的目的是将任意形状的数组扁平化，变为 1 维数组
# 其中，a 表示需要处理的数组。order 表示变换时的读取顺序，
# 默认是按照行依次读取，当 order='F' 时，可以按列依次读取排序。：
arr_r = np.ravel(arr_reshape,order='C')
print(arr_r)

# 轴移动
# numpy.moveaxis(a, source, destination)

    # a：数组。
    # source：要移动的轴的原始位置。
    # destination：要移动的轴的目标位置。

a = np.ones((1,2,3))
a_new = np.moveaxis(a,0,2)
print(a.shape,a_new.shape)

# 轴交换
# 和 moveaxis 不同的是，
# swapaxes 可以用来交换数组的轴。其方法如下：
# numpy.swapaxes(a, axis1, axis2)

    # a：数组。
    # axis1：需要交换的轴 1 位置。
    # axis2：需要与轴 1 交换位置的轴 1 位置。
a2 = np.ones((1,4,3))
a_new2 = np.swapaxes(a2,0,2)
print(a2.shape,a_new2.shape)

# 数组转置

# transpose 类似于矩阵的转置，
# 它可以将 2 维数组的横轴和纵轴交换。其方法如下：
# numpy.transpose(a, axes=None)
a3 = np.arange(4).reshape((2,2))
a3_T = np.transpose(a3)

# 维度改变
# atleast_xd 支持将输入数据直接视为 x维。
# 这里的 x 可以表示：1，2，3
arr_1d = np.atleast_1d([1,2,3])
arr_2d = np.atleast_2d([4,5,6])
arr_3d = np.atleast_3d([7,8,9])
print(arr_1d,'\n',arr_2d,'\n',arr_3d)
print(arr_1d.shape,arr_2d.shape,arr_3d.shape)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[0 3 6 1 4 7 2 5 8]
(1, 2, 3) (2, 3, 1)
(1, 4, 3) (3, 4, 1)
[1 2 3] 
 [[4 5 6]] 
 [[[7]
  [8]
  [9]]]
(3,) (1, 3) (1, 3, 1)


In [7]:
# 类型转换
# 在 NumPy 中，还有一系列以 as 开头的方法，
# 它们可以将特定输入转换为数组，亦可将数组转换为矩阵、
# 标量，ndarray 等。
#   asarray(a，dtype，order)：将特定输入转换为数组。
#   asanyarray(a，dtype，order)：将特定输入转换为 ndarray。
#   asmatrix(data，dtype)：将特定输入转换为矩阵。
#   asfarray(a，dtype)：将特定输入转换为 float 类型的数组。
#   asarray_chkfinite(a，dtype，order)：将特定输入转换为数组，
#   检查 NaN 或 infs。
#   asscalar(a)：将大小为 1 的数组转换为标量。
a = np.arange(4).reshape((2,2))
arr_matrix = np.asmatrix(a)
print(arr_matrix)


[[0 1]
 [2 3]]


In [14]:
# 数组连接
# numpy.concatenate((a1, a2, ...), axis=0)
#   (a1, a2, ...)：需要连接的数组。
#   axis：指定连接轴。0 :纵向
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8],[9,10]])
c = np.array([[11,12]])

d = np.concatenate((a,b,c),axis=0)
e = np.concatenate((a.T,b),axis=1)
print(e)


[[ 1  3  5  7  8]
 [ 2  4  6  9 10]]


In [23]:
# 数组堆叠
# • stack(arrays，axis)：沿着新轴连接数组的序列。
# • column_stack()：将 1 维数组作为列堆叠到 2 维数组中。
# • hstack()：按水平方向堆叠数组。
# • vstack()：按垂直方向堆叠数组。
# • dstack()：按深度方向堆叠数组。
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = np.stack((a,b),axis=0)
d = np.stack((a,b),axis=1)
print(c,'\n',d)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
# 拆分
# • split(ary，indices_or_sections，axis)：
# 将数组拆分为多个子数组。
# • dsplit(ary，indices_or_sections)：
# 按深度方向将数组拆分成多个子数组。
# • hsplit(ary，indices_or_sections)：
# 按水平方向将数组拆分成多个子数组。
# • vsplit(ary，indices_or_sections)：
# 按垂直方向将数组拆分成多个子数组
a = np.arange(10)
b = np.arange(10).reshape(2,5)
c = np.split(a,5)
d = np.split(b,2)
print(b,'\n',d)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 [array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]


In [41]:
# 删除
# delete(arr，obj，axis)：沿特定轴删除数组中的子数组
a = np.arange(12).reshape((3,4))
b = np.delete(a,2,axis=0)
c = np.delete(a,2,axis=1)
print(a,'\n',b,'\n',c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [[0 1 2 3]
 [4 5 6 7]] 
 [[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


In [49]:
# 数组插入
# insert(arr，obj，values，axis)：依据索引在特定轴之前插入值。
a = np.arange(12).reshape((3,4))
b = np.arange(4)
c = np.insert(a,2,b,axis=0)
print(c)
# 附加
# append(arr，values，axis)：将值附加到数组的末尾，并返回 1 维数组。
e = np.arange(6).reshape((2,3))
f = np.arange(3)
g = np.append(e,f)
print(g)
# 注意 append方法返回值，默认是展平状态下的 1 维数组。
# 重设尺寸
# resize(a，new_shape)：对数组尺寸进行重新设定。
# reshape 在改变形状时，不会影响原数组，
# 相当于对原数组做了一份拷贝。
# 而 resize 则是对原数组执行操作。
g.resize((3,3))
print(g)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
[0 1 2 3 4 5 0 1 2]
[[0 1 2]
 [3 4 5]
 [0 1 2]]


In [51]:
# 翻转数组
# fliplr(m)：左右翻转数组。
# flipud(m)：上下翻转数组。
a = np.arange(16).reshape((4,4))
print(a)
print(np.fliplr(a))
print(np.flipud(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [62]:
# 随机数
# numpy.random.rand(d0, d1, ..., dn) 
# 方法的作用为：指定一个数组，并使用 [0, 1) 
# 区间随机数据填充，这些数据均匀分布。
array_rand = np.random.rand(2,5)
print(array_rand)

# numpy.random.randn(d0, d1, ..., dn)
# 从标准正态分布中返回一个或多个样本值
array_randn = np.random.randn(2,5)
print(array_randn)

# randint(low, high, size, dtype) 
# 生成 [low, high) 的随机整数。注意这是一个半开半闭区间。
arr_randi = np.random.randint(1,10,9)
print(arr_randi.reshape((3,3)))

# random_sample(size)
# 在 [0, 1) 区间内生成指定 size 的随机浮点数。
arr_rs = np.random.random_sample([10])
print(arr_rs.reshape((2,5)))
# numpy.random.random([size])
# numpy.random.ranf([size])
# numpy.random.sample([size])

# choice(a, size, replace, p)
# 给定的数组里随机抽取几个值，该方法类似于随机抽样。
arr_choice = np.random.choice(10,5)
print(arr_choice)

[[0.76296864 0.39229161 0.87553858 0.2714912  0.34641361]
 [0.52619478 0.65873151 0.65001914 0.45688572 0.3129794 ]]
[[-0.29731453 -0.64527255  2.61917701 -0.11775486  0.498504  ]
 [-0.16275684  0.7738028  -2.04519289  0.7609462   0.51114921]]
[[1 9 2]
 [4 7 1]
 [6 9 5]]
[[0.00679503 0.16993901 0.99073762 0.90512952 0.78091239]
 [0.76510004 0.24551232 0.37854137 0.52878842 0.44534189]]
[8 6 9 0 5]


In [63]:
# 概率密度分布
# numpy.random.beta(a，b，size)：
# 从 Beta 分布中生成随机数。

# • numpy.random.binomial(n, p, size)：
# 从二项分布中生成随机数。

# • numpy.random.chisquare(df，size)：
# 从卡方分布中生成随机数。

# • numpy.random.dirichlet(alpha，size)：
# 从 Dirichlet 分布中生成随机数。

# • numpy.random.exponential(scale，size)：
# 从指数分布中生成随机数。

# • numpy.random.f(dfnum，dfden，size)：
# 从 F 分布中生成随机数。

# • numpy.random.gamma(shape，scale，size)：
# 从 Gamma 分布中生成随机数。

# • numpy.random.geometric(p，size)：
# 从几何分布中生成随机数。

# • numpy.random.gumbel(loc，scale，size)：
# 从 Gumbel 分布中生成随机数。
 
#   numpy.random.hypergeometric(ngood, nbad, nsample, size)：
#   从超几何分布中生成随机数。

# • numpy.random.laplace(loc，scale，size)：
# 从拉普拉斯双指数分布中生成随机数。

# • numpy.random.logistic(loc，scale，size)：
# 从逻辑分布中生成随机数。

# • numpy.random.lognormal(mean，sigma，size)：
# 从对数正态分布中生成随机数。

# • numpy.random.logseries(p，size)：
# 从对数系列分布中生成随机数。

# • numpy.random.multinomial(n，pvals，size)：
# 从多项分布中生成随机数。

# • numpy.random.multivariate_normal(mean, cov, size)：
# 从多变量正态分布绘制随机样本。

# • numpy.random.negative_binomial(n, p, size)：
# 从负二项分布中生成随机数。

# • numpy.random.noncentral_chisquare(df，nonc，size)：
# 从非中心卡方分布中生成随机数。

# • numpy.random.noncentral_f(dfnum, dfden, nonc, size)：
# 从非中心 F 分布中抽取样本。

# 1. numpy.random.normal(loc，scale，size)：
# 从正态分布绘制随机样本。

# • numpy.random.pareto(a，size)：
# 从具有指定形状的 Pareto II 或 Lomax 分布中生成随机数。

# • numpy.random.poisson(lam，size)：
# 从泊松分布中生成随机数。

# • numpy.random.power(a，size)：
# 从具有正指数 a-1 的功率分布中在 0，1 中生成随机数。

# • numpy.random.rayleigh(scale，size)：
# 从瑞利分布中生成随机数。

# • numpy.random.standard_cauchy(size)：
# 从标准 Cauchy 分布中生成随机数。

# • numpy.random.standard_exponential(size)：
# 从标准指数分布中生成随机数。

# • numpy.random.standard_gamma(shape，size)：
# 从标准 Gamma 分布中生成随机数。

# • numpy.random.standard_normal(size)：
# 从标准正态分布中生成随机数。

# • numpy.random.standard_t(df，size)：
# 从具有 df 自由度的标准学生 t 分布中生成随机数。

# 1. numpy.random.triangular(left，mode，right，size)：
# 从三角分布中生成随机数。

# • numpy.random.uniform(low，high，size)：
# 从均匀分布中生成随机数。

# • numpy.random.vonmises(mu，kappa，size)：
# 从 von Mises 分布中生成随机数。

# • numpy.random.wald(mean，scale，size)：
# 从 Wald 或反高斯分布中生成随机数。

# • numpy.random.weibull(a，size)：
# 从威布尔分布中生成随机数。

# • numpy.random.zipf(a，size)：
# 从 Zipf 分布中生成随机数。

In [77]:
# 数学函数
# 三角函数
# • numpy.sin(x)：三角正弦。
# • numpy.cos(x)：三角余弦。
# • numpy.tan(x)：三角正切。
# • numpy.arcsin(x)：三角反正弦。
# • numpy.arccos(x)：三角反余弦。
# • numpy.arctan(x)：三角反正切。
# • numpy.hypot(x1,x2)：直角三角形求斜边。
# • numpy.degrees(x)：弧度转换为度。
# 1. numpy.radians(x)：度转换为弧度。
# • numpy.deg2rad(x)：度转换为弧度。
# • numpy.rad2deg(x)：弧度转换为度

# 双曲函数
# • numpy.sinh(x)：双曲正弦。
# • numpy.cosh(x)：双曲余弦。
# • numpy.tanh(x)：双曲正切。
# • numpy.arcsinh(x)：反双曲正弦。
# • numpy.arccosh(x)：反双曲余弦。
# • numpy.arctanh(x)：反双曲正切

# 数值修约
# 数值修约, 又称数字修约, 是指在进行具体的数字运算前, 
# 按照一定的规则确定一致的位数, 然后舍去某些数字后面多余的尾数的过程。
# 比如, 我们常听到的「4 舍 5 入」就属于数值修约中的一种。
# • numpy.around(a)：平均到给定的小数位数。
# • numpy.round_(a)：将数组舍入到给定的小数位数。
# • numpy.rint(x)：修约到最接近的整数。
# • numpy.fix(x, y)：向 0 舍入到最接近的整数。
# • numpy.floor(x)：返回输入的底部(标量 x 的底部是最大的整数 i)。
# • numpy.ceil(x)：返回输入的上限(标量 x 的底部是最小的整数 i).
# • numpy.trunc(x)：返回输入的截断值。
a = np.random.randn(5)*10
# print(a)
# print(np.around(a))
# print(np.round_(a))
# print(np.rint(a))
# print(np.fix(a))
# print(np.trunc(a))

# 求和、求积、差分
# numpy.prod(a, axis, dtype, keepdims)：
# 返回指定轴上的数组元素的乘积。
# • numpy.sum(a, axis, dtype, keepdims)：
# 返回指定轴上的数组元素的总和。
# • numpy.nanprod(a, axis, dtype, keepdims)
# ：返回指定轴上的数组元素的乘积, 将 NaN 视作 1。
# • numpy.nansum(a, axis, dtype, keepdims)：
# 返回指定轴上的数组元素的总和, 将 NaN 视作 0。
# • numpy.cumprod(a, axis, dtype)：
# 返回沿给定轴的元素的累积乘积。
# • numpy.cumsum(a, axis, dtype)：
# 返回沿给定轴的元素的累积总和。
# • numpy.nancumprod(a, axis, dtype)：
# 返回沿给定轴的元素的累积乘积, 将 NaN 视作 1。
# • numpy.nancumsum(a, axis, dtype)：
# 返回沿给定轴的元素的累积总和, 将 NaN 视作 0。
# • numpy.diff(a, n, axis)：
# 计算沿指定轴的第 n 个离散差分。
# • numpy.ediff1d(ary, to_end, to_begin)：
# 数组的连续元素之间的差异。
# numpy.gradient(f)：
# 返回 N 维数组的梯度。
# numpy.cross(a, b, axisa, axisb, axisc, axis)：
# 返回两个(数组）向量的叉积。
# • numpy.trapz(y, x, dx, axis)：
# 使用复合梯形规则沿给定轴积分

arr_sum = np.arange(10).reshape((2,5))
print(arr_sum)
print(np.sum(arr_sum,axis=0))

# 指数和对数
# numpy.exp(x)：计算输入数组中所有元素的指数。
# numpy.log(x)：计算自然对数。
# numpy.log10(x)：计算常用对数。
# numpy.log2(x)：计算二进制对数。

# 算术运算
# • numpy.add(x1, x2)：对应元素相加。
#   numpy.reciprocal(x)：求倒数 1/x。
# • numpy.negative(x)：求对应负数。
# • numpy.multiply(x1, x2)：求解乘法。
# • numpy.divide(x1, x2)：相除 x1/x2。
# • numpy.power(x1, x2)：类似于 x1^x2。
# • numpy.subtract(x1, x2)：减法。
# • numpy.fmod(x1, x2)：返回除法的元素余项。
# • numpy.mod(x1, x2)：返回余项。
#   numpy.modf(x1)：返回数组的小数和整数部分。
# • numpy.remainder(x1, x2)：返回除法余数。

# 矩阵和向量积
# • numpy.dot(a, b)：求解两个数组的点积。
# • numpy.vdot(a, b)：求解两个向量的点积。
# • numpy.inner(a, b)：求解两个数组的内积。
# • numpy.outer(a, b)：求解两个向量的外积。
# • numpy.matmul(a, b)：求解两个数组的矩阵乘积。
# • numpy.tensordot(a, b)：求解张量点积。
# • numpy.kron(a, b)：计算 Kronecker 乘积。

# 其他:
#   numpy.angle(z, deg)：返回复参数的角度。
# • numpy.real(val)：返回数组元素的实部。
# • numpy.imag(val)：返回数组元素的虚部。
# • numpy.conj(x)：按元素方式返回共轭复数。
# • numpy.convolve(a, v, mode)：返回线性卷积。
# • numpy.sqrt(x)：平方根。
# • numpy.cbrt(x)：立方根。
# • numpy.square(x)：平方。
# • numpy.absolute(x)：绝对值, 可求解复数。
# • numpy.fabs(x)：绝对值。
# • numpy.sign(x)：符号函数。
# • numpy.maximum(x1, x2)：最大值。
#   numpy.minimum(x1, x2)：最小值。
# • numpy.nan_to_num(x)：用 0 替换 NaN。
# • numpy.interp(x, xp, fp, left, right, period)：线性插值。

# 代数运算
# • numpy.linalg.cholesky(a)：
# Cholesky 分解。
# • numpy.linalg.qr(a ,mode)：
# 计算矩阵的 QR 因式分解。
# • numpy.linalg.svd(a ,full_matrices,compute_uv)：
# 奇异值分解。
# • numpy.linalg.eig(a)：
# 计算正方形数组的特征值和右特征向量。
# • numpy.linalg.eigh(a, UPLO)：
# 返回 Hermitian 或对称矩阵的特征值和特征向量。
# • numpy.linalg.eigvals(a)：
# 计算矩阵的特征值。
# • numpy.linalg.eigvalsh(a, UPLO)：
# 计算 Hermitian 或真实对称矩阵的特征值。
# • numpy.linalg.norm(x ,ord,axis,keepdims)：
# 计算矩阵或向量范数。
# • numpy.linalg.cond(x ,p)：
# 计算矩阵的条件数。
#   numpy.linalg.det(a)：
#   计算数组的行列式。
# • numpy.linalg.matrix_rank(M ,tol)：
# 使用奇异值分解方法返回秩。
# • numpy.linalg.slogdet(a)：
# 计算数组的行列式的符号和自然对数。
# • numpy.trace(a ,offset,axis1,axis2,dtype,out)：
# 沿数组的对角线返回总和。
# • numpy.linalg.solve(a, b)：
# 求解线性矩阵方程或线性标量方程组。
# • numpy.linalg.tensorsolve(a, b ,axes)：
# 为 x 解出张量方程 a x = b
# • numpy.linalg.lstsq(a, b ,rcond)：
# 将最小二乘解返回到线性矩阵方程。
# • numpy.linalg.inv(a)：
# 计算逆矩阵。
# • numpy.linalg.pinv(a ,rcond)：
# 计算矩阵的（Moore-Penrose）伪逆。
# • numpy.linalg.tensorinv(a ,ind)：
# 计算 N 维数组的逆。

[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 5  7  9 11 13]


In [15]:
# 数组索引和切片
# 数组索引
arr_index_2d = np.arange(30).reshape((5,6))
print(arr_index_2d)
print(arr_index_2d[[1,2],[3,4]])

arr_index_3d =np.arange(30).reshape((2,3,5))
print(arr_index_3d)
print(arr_index_3d[[0,1],[1,2],[1,2]])

# 数组切片
# Ndarray[start:stop:step]

# 排序、搜索、计数
# 排序
# numpy.sort(a, axis=-1, kind='quicksort', order=None)
# • a：数组。
# • axis：要排序的轴。
# 如果为None，则在排序之前将数组铺平。默认值为 -1，沿最后一个轴排序。
# • kind：{'quicksort'，'mergesort'，'heapsort'}，
# 排序算法。默认值为 quicksort。

a = np.arange(20).reshape((4,5))
print(np.sort(a))
# 除了 numpy.sort，还有这样一些对数组进行排序的方法：
# • numpy.lexsort(keys ,axis)：使用多个键进行间接排序。
# • numpy.argsort(a ,axis,kind,order)：沿给定轴执行间接排序。
# • numpy.msort(a)：沿第 1 个轴排序。
# • numpy.sort_complex(a)：针对复数排序。

# 搜索和计数
# argmax(a ,axis,out)：
# 返回数组中指定轴的最大值的索引。
# • nanargmax(a ,axis)：
# 返回数组中指定轴的最大值的索引,忽略 NaN。
# • argmin(a ,axis,out)：
# 返回数组中指定轴的最小值的索引。
# • nanargmin(a ,axis)：
# 返回数组中指定轴的最小值的索引,忽略 NaN。
# • argwhere(a)：
# 返回数组中非 0 元素的索引,按元素分组。
# • nonzero(a)：
# 返回数组中非 0 元素的索引。
# • flatnonzero(a)：
# 返回数组中非 0 元素的索引,并铺平。
# • where(条件,x,y)：
# 根据指定条件,从指定行、列返回元素。
# • searchsorted(a,v ,side,sorter)：
# 查找要插入元素以维持顺序的索引。
#  extract(condition,arr)：
#  返回满足某些条件的数组的元素。
# • count_nonzero(a)：
# 计算数组中非 0 元素的数量。
a = np.random.randint(0,10,20)
print(a)
print(np.argmax(a))
print(np.argmin(a))
print(np.nonzero(a))
print(np.count_nonzero(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[ 9 16]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[ 6 27]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[2 7 1 9 7 1 8 5 8 7 5 6 2 1 4 0 0 7 3 0]
3
15
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 17, 18],
      dtype=int64),)
17
