In [6]:
# 导入 NumPy
import numpy as np

In [7]:
# 2. 查看 NumPy 版本信息
print(np.__version__)

1.16.4


In [6]:
# 3. 通过列表创建一维数组
np.array([1,2,3])

array([1, 2, 3])

In [7]:
# 4.通过列表创建二维数组
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 5. 创建全为 0 的二维数组
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
#6.创建全为 1 的三维数组
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
#7.创建一维等差数组
np.linspace(0,10,num=10,endpoint=False)
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 8.创建二维等差数组
np.arange(6).reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
# 9.创建单位矩阵（二维数组）
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# 10.创建等间隔一维数组
np.linspace(0,10,6)

[[0.73927763 0.02140136 0.03277808]
 [0.9190231  0.93523006 0.33340317]
 [0.23466355 0.95677191 0.25630169]]


In [26]:
# 11.创建二维随机数组
print(np.random.rand(3,3))

[[0.94135382 0.37801723 0.21846342]
 [0.74710315 0.91504277 0.09286747]
 [0.61453262 0.16378011 0.88553146]]


In [28]:
# 12.创建二维随机整数数组（数值小于 5）
print(np.random.randint(0,5,size=(3,3)))

[[2 4 2]
 [1 4 4]
 [0 1 3]]


In [40]:
# 13. 依据自定义函数创建数组
def return_minus(x):
    return x-1
arr_func = np.fromfunction(return_minus,(5,))
print(arr_func)

[-1.  0.  1.  2.  3.]


In [ ]:
# 数组运算
# 14.一维数组加法运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

In [45]:
# 15.一维数组减法运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a-b)

[-3 -3 -3]


In [49]:
# 16.一维数组乘法运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)

[ 4 10 18]


In [50]:
# 17. 一维数组除法运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a/b)

[0.25 0.4  0.5 ]


In [58]:
a_2d = np.array([[1,2],[3,4]])
b_2d = np.array([[5,6],[7,8]])
# 18. 矩阵加法运算
print(a_2d+b_2d)
# 19. 矩阵减法运算
print(a_2d-b_2d)
# 20. 矩阵元素间乘法运算
print(a_2d*b_2d)
# 21. 矩阵乘法运算
print(np.dot(a_2d,b_2d))
# 22. 数乘矩阵
print(a_2d*2)
# 23. 矩阵的转置
print(a_2d.T)
print(np.transpose(a_2d))
print(a_2d.transpose())
# 24. 矩阵求逆
print(np.linalg.inv(a_2d))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[2 4]
 [6 8]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [77]:
# 数学函数
# 25.三角函数
a = np.array([0,1,2])
print(np.sin(a))

[0.         0.84147098 0.90929743]


In [83]:
# 26.以自然对数函数为底数的指数函数
np.exp(a)
# 27. 数组的方根的运算（开平方）
print(np.sqrt(a))
print(np.power(a,0.5))
# 28. 数组的方根的运算（立方）
print(np.power(a,3))

[0.         1.         1.41421356]
[0.         1.         1.41421356]
[0 1 8]


In [98]:
# 数组切片和索引
# 一维数组索引
a = np.array([1,2,3])
print(a[0],a[-1])
# 一维数组切片
print(a[:2],a[:-1])
# 二维数组索引
a_2d = np.arange(16).reshape((4,4))
print(a_2d[2,3],'\n',a_2d[-1,-1])
# 二维数组切片（取第 2 列）
print(a_2d[:,1])
# 二维数组切片（取第 2，3 行）
print(a_2d[1:3,:])

1 3
[1 2] [1 2]
11 
 15
[ 1  5  9 13]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 数组形状操作
a = np.random.rand(3,2)

In [ ]:
# 查看数组形状
print(a.shape)

In [ ]:
# 更改数组形状（不改变原始数组）
b = a.reshape(2,3)

In [ ]:
# 更改数组形状（改变原始数组）
b.resize(3,2)

In [ ]:
# 37. 展平数组
np.ravel(a)

In [55]:
# 38. 垂直拼合数组
a = np.random.randint(10, size=(3, 3))
b = np.random.randint(10, size=(3, 3))
c = np.vstack((a,b))
print(c)

[[8 8 0]
 [4 5 5]
 [7 8 3]
 [6 4 4]
 [6 0 8]
 [8 7 6]]


In [53]:
# 水平拼合数组
np.hstack((a,b))

array([[0, 4, 7, 0, 1, 2],
       [7, 7, 6, 1, 9, 8],
       [0, 6, 0, 8, 6, 3]])

In [107]:
# 沿纵轴分割数组
print(a)
np.vsplit(a,3)

[[2 5 6]
 [9 9 8]
 [4 5 9]]


[array([[2, 5, 6]]), array([[9, 9, 8]]), array([[4, 5, 9]])]

In [54]:
# 数组排序
a = np.array(([1, 4, 3], [6, 2, 9], [4, 7, 2]))
# 返回每列最大值
print(np.max(a,axis=1))
# 返回每行最小值
print(np.min(a,axis=0))
# 返回每列最大值索引
print(np.argmax(a,axis=1))
# 返回每行最小值索引
print(np.argmin(a,axis=0))

[4 9 7]
[1 2 2]
[1 2 1]
[0 1 2]


In [119]:
# 数组统计
# 统计数组各列的中位数(这里的0,1表示行列和上面的最值的表示相反)
print(np.median(a,axis=0))
# 统计数组各行的算术平均值
print(np.mean(a,axis=1))
# 统计数组各列的加权平均值
print(np.average(a,axis=0))
# 统计数组各行的方差
print(np.var(a,axis=1))
# 统计数组各列的标准偏差
print(np.std(a,axis=0))

[4. 4. 3.]
[2.66666667 5.66666667 4.33333333]
[3.66666667 4.33333333 4.66666667]
[1.55555556 8.22222222 4.22222222]
[2.05480467 2.05480467 3.09120617]


In [14]:
# 创建一个 5x5 的二维数组，其中边界值为1，其余值为0
z = np.ones((5,5))
z[1:-1,1:-1] = 0 
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [145]:
# 使用数字 0 将一个全为 1 的 5x5 二维数组包围?
z3 = np.ones((5,5))
# numpy.pad(array, pad_width, mode='constant', **kwargs)
# array为要填补的数组
# pad_width是在各维度的各个方向上想要填补的长度,如（（1，2），（2，2）），
# 表示在第一个维度上水平方向上padding=1,垂直方向上padding=2,
# 在第二个维度上水平方向上padding=2,垂直方向上padding=2。
# 如果直接输入一个整数，则说明各个维度和各个方向所填补的长度都一样。
#  mode为填补类型，即怎样去填补，有“constant”，“edge”等模式，
# 如果为constant模式，就得指定填补的值，如果不指定，则默认填充0
z3 = np.pad(z,pad_width=[(1,1),(1,1)],mode='constant',constant_values=0)
print(z3)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [151]:
# 创建一个 5x5 的二维数组，并设置值 1, 2, 3, 4 落在其对角线下方
# 对角矩阵
# numpy.diag(v,k=0)
#     v : array_like.
#
# 如果v是2D数组，返回k位置的对角线。
# 
# 如果v是1D数组，返回一个v作为k位置对角线的2维数组。
# 
#     k : int, optional
# 
# 对角线的位置，大于零位于对角线上面，小于零则在下面。
z = np.diag(np.linspace(1,5,num=4,endpoint=False),k=-1)
print(z)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [17]:
# 创建一个 10x10 的二维数组，并使得 1 和 0 沿对角线间隔放置
z = np.random.randint(1,10,size=(10,10))

for x in range(np.shape(z)[0]):
    for y in range(np.shape(z)[1]):
        if x == y and x%2!=0 :
            z[x,y] = 0
        elif x == y and x%2==0 :
            z[x,y] = 1
z

array([[1, 6, 8, 7, 6, 8, 2, 5, 3, 6],
       [1, 0, 9, 7, 1, 5, 7, 7, 3, 7],
       [7, 7, 1, 1, 5, 8, 4, 2, 5, 7],
       [5, 1, 6, 0, 4, 5, 3, 4, 6, 5],
       [5, 9, 7, 8, 1, 9, 9, 6, 7, 9],
       [2, 9, 8, 9, 8, 0, 4, 5, 8, 1],
       [2, 6, 3, 7, 1, 9, 1, 7, 7, 8],
       [2, 9, 4, 9, 8, 5, 1, 0, 9, 9],
       [6, 3, 1, 8, 3, 4, 3, 4, 1, 7],
       [6, 9, 7, 8, 4, 6, 5, 5, 3, 0]])

In [24]:
# 创建一个 0-10 的一维数组，并将 (1, 9] 之间的数全部反转成负数
arr_ar = np.arange(11)
# 方案1
np.where((arr_ar>1)&(arr_ar<=9),arr_ar*-1,arr_ar)
# 方案2
arr_ar[(1<arr_ar)&(arr_ar<=9)]*=-1
print(arr_ar)

[ 0  1 -2 -3 -4 -5 -6 -7 -8 -9 10]


In [25]:
# 找出两个一维数组中相同的元素
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[9 4 0 5 0 6 6 3 2 0]
[7 6 2 6 7 1 4 6 8 6]
[2 4 6]


In [19]:
# 使用 NumPy 打印昨天、今天、明天的日期?
yesterday = np.datetime64('today','D') - np.timedelta64('1','D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64('1','D')
print(yesterday,today,tomorrow)

2019-09-01 2019-09-02 2019-09-03
原始值 [9.43896629 4.81818089 5.36543199 5.50307431 5.7928487  2.40307214
 7.55898615 4.40085606 0.92247309 2.29850771]
方法1: [9 4 5 5 5 2 7 4 0 2]
方法2: [9. 4. 5. 5. 5. 2. 7. 4. 0. 2.]
方法3: [9. 4. 5. 5. 5. 2. 7. 4. 0. 2.]
方法4: [9. 5. 5. 6. 6. 2. 8. 4. 1. 2.]
方法2: [9. 4. 5. 5. 5. 2. 7. 4. 0. 2.]


In [ ]:
# 使用五种不同的方法去提取一个随机数组的整数部分
arr_rondom = np.random.uniform(0,10,10)
print('原始值',arr_rondom)
print('方法1:',arr_rondom.astype(int))
print('方法2:',np.trunc(arr_rondom))
print('方法3:',np.floor(arr_rondom))
print('方法4:',np.around(arr_rondom))
print('方法2:',arr_rondom-arr_rondom%1)

In [27]:
# 创建一个 5x5 的矩阵，其中每行的数值范围从 1 到 5
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [18]:
# 创建一个长度为 5 的等间隔一维数组，
# 其值域范围从 0 到 1，但是不包括 0 和 1
np.linspace(0,1,num=6,endpoint=False)[1:]

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

In [7]:
# 创建一个长度为10的随机一维数组，并将其按升序排序
arr_random = np.random.rand(10)
print(np.sort(arr_random))
arr_random.sort()
print(arr_random)

[0.0915269  0.11309697 0.12621098 0.16663969 0.33363269 0.33869234
 0.45595928 0.56737299 0.74659415 0.83996754]
[0.0915269  0.11309697 0.12621098 0.16663969 0.33363269 0.33869234
 0.45595928 0.56737299 0.74659415 0.83996754]


In [10]:
# 创建一个 3x3 的二维数组，并将列按升序排序
arr_random = np.random.rand(3,3)
arr_random.sort(axis=0)
print(arr_random)

[[0.10782152 0.0622213  0.01948609]
 [0.2346158  0.10984742 0.30677215]
 [0.42304902 0.62915143 0.34724743]]


In [14]:
# 创建一个长度为 5 的一维数组，并将其中最大值替换成 0
z = np.random.rand(5)
z[np.argmax(z)] = 0
z[z.argmax()] = 0
print(z)

[0.2968607  9.         0.21596632 0.05273708 0.        ]


In [23]:
# 打印每个 NumPy 标量类型的最小值和最大值
for dtype in [np.int8,np.int32,np.int64]:
    print('The minimum value of {}:'.format(dtype),np.iinfo(dtype).min)
    print('The maximum value of {}:'.format(dtype),np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print('The minimum value of {}:'.format(dtype),np.iinfo(dtype).min)
    print('The maximum value of {}:'.format(dtype),np.iinfo(dtype).max)

The minimum value of <class 'numpy.int8'>: -128
The maximum value of <class 'numpy.int8'>: 127
The minimum value of <class 'numpy.int32'>: -2147483648
The maximum value of <class 'numpy.int32'>: 2147483647
The minimum value of <class 'numpy.int64'>: -9223372036854775808
The maximum value of <class 'numpy.int64'>: 9223372036854775807


ValueError: Invalid integer data type 'f'.

In [29]:
# 将 float32 转换为整型
z = np.arange(10,dtype=np.float32)
print(z)
z = z.astype(np.int32,copy=False)
print(z)#%%

# 将随机二维数组按照第 3 列从上到下进行升序排列
z = np.random.randint(0,10,(5,5))
print('排列前',z)
print('排列后',z[z[:,2].argsort()])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


In [30]:
# 从随机一维数组中找出距离给定数值（0.5）最近的数
z = np.random.randint(0,10,size=(5,))
value = 0.5
m = z[np.abs(z-value).argmin()]
print(z)
print(m)

[1 6 4 7 1]
1


In [34]:
# 将二维数组的前两行进行顺序交换
a = np.arange(10).reshape((2,-1))
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [35]:
# 找出随机一维数组中出现频率最高的值
z = np.random.randint(0,10,50)
# print(z)
print(np.bincount(z))
print(z[np.bincount(z).argmax()],np.bincount(z).max())

[ 5 10  4  4  5  4  7  2  2  7]
9 10


In [55]:
# 找出给定一维数组中非 0 元素的位置索引
z = np.nonzero([1,0,2,-1,0,0])
print(z)

(array([0, 2, 3], dtype=int64),)


In [77]:
# 71. 对于给定的 5x5 二维数组，在其内部随机放置 p 个值为 1 的数
p = 3
z = np.zeros((5,5))
# 方案1
# for i in range(p):
#     z[np.random.randint(0,5),np.random.randint(0,5)]=1
# 方案2
np.put(z,np.random.choice(range(5*5),p),1)
print(np.random.choice(range(5*5),p))
print(z)

[12 19 17]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [87]:
# 对于随机的 3x3 二维数组，减去数组每一行的平均值
z = np.random.randint(0,10,size=(3,3))
print(z)
z = z-z.mean(axis=1,keepdims=True)
z2 = z-z.mean(axis=1,keepdims=False)
print(z)
print(z2)

[[3 7 7]
 [9 3 5]
 [6 2 0]]
[[-2.66666667  1.33333333  1.33333333]
 [ 3.33333333 -2.66666667 -0.66666667]
 [ 3.33333333 -0.66666667 -2.66666667]]
[[-2.66666667  1.33333333  1.33333333]
 [ 3.33333333 -2.66666667 -0.66666667]
 [ 3.33333333 -0.66666667 -2.66666667]]


In [92]:
# 获得二维数组点积结果的对角线数组
a = np.random.uniform(0,1,(3,3))
b = np.random.uniform(0,1,(3,3))
print(np.dot(a,b))
# 方案1(较慢)
print(np.diag(np.dot(a,b)))
#方案2(较快)
print(np.sum(a*b.T,axis=1))
# 方案3?
print(np.einsum("ij, ji->i", a, b))

[[0.57157042 0.56505754 0.59457255]
 [1.02857591 1.0021828  1.26773944]
 [1.24279176 0.98014404 1.06193241]]
[0.57157042 1.0021828  1.06193241]
[0.57157042 1.0021828  1.06193241]
[0.57157042 1.0021828  1.06193241]


In [100]:
# 找到随机一维数组中前 p 个最大值
p = 5 
z = np.random.randint(0,100,50)
print(z[z.argsort()[-p:]])

[92 93 94 95 96]


In [104]:
# 计算随机一维数组中每个元素的 4 次方数值
z = np.random.randint(0,5,5)
x = np.power(z,4)
print(z)
print(x)

[0 4 4 3 2]
[  0 256 256  81  16]


In [36]:
# 对于二维随机数组中各元素，保留其 2 位小数
z = np.random.rand(5,5)
print(z)
np.set_printoptions(precision=2)
print(z)

[[0.07476803 0.0587384  0.15870602 0.66457818 0.52899374]
 [0.86705646 0.88129596 0.4654572  0.12472989 0.37269547]
 [0.9037412  0.00592605 0.61343266 0.52615994 0.53693375]
 [0.75004973 0.47592584 0.96146286 0.60835203 0.89991958]
 [0.47958606 0.23456709 0.29409637 0.49391422 0.52666016]]
[[0.07 0.06 0.16 0.66 0.53]
 [0.87 0.88 0.47 0.12 0.37]
 [0.9  0.01 0.61 0.53 0.54]
 [0.75 0.48 0.96 0.61 0.9 ]
 [0.48 0.23 0.29 0.49 0.53]]


In [9]:
# 使用科学记数法输出 NumPy 数组
z = np.random.rand(5,5)
print(z)
print(z/1e3)

[[0.20002526 0.68856384 0.37469892 0.98436781 0.61161833]
 [0.45857693 0.10772723 0.4084114  0.18934691 0.7178853 ]
 [0.07191452 0.91908819 0.69334289 0.83044294 0.18563834]
 [0.77776026 0.39470653 0.2572925  0.63192333 0.64829308]
 [0.2233924  0.35650551 0.15540514 0.45259592 0.06385814]]
[[2.00025260e-04 6.88563835e-04 3.74698922e-04 9.84367810e-04
  6.11618329e-04]
 [4.58576931e-04 1.07727229e-04 4.08411396e-04 1.89346914e-04
  7.17885304e-04]
 [7.19145176e-05 9.19088186e-04 6.93342893e-04 8.30442939e-04
  1.85638344e-04]
 [7.77760260e-04 3.94706526e-04 2.57292498e-04 6.31923334e-04
  6.48293076e-04]
 [2.23392399e-04 3.56505510e-04 1.55405136e-04 4.52595919e-04
  6.38581427e-05]]


In [13]:
# 使用 NumPy 找出百分位数（25%，50%，75%）
z = np.arange(10)
print(z)
print(np.percentile(z,q=[25,50,75]))

[0 1 2 3 4 5 6 7 8 9]
[2.25 4.5  6.75]


In [39]:
# 找出数组中缺失值的总数及所在位置
z = np.random.rand(5,5)
z[np.random.randint(5,size=5),np.random.randint(5,size=5)]=np.nan
print('缺失值总量:',np.isnan(z).sum())
print('缺失值索引:',np.where(np.isnan(z)))
print(z)

缺失值总量: 4
缺失值索引: (array([2, 2, 2, 4], dtype=int64), array([2, 3, 4, 0], dtype=int64))
[[0.25 0.82 0.08 0.15 0.72]
 [0.62 0.65 0.41 0.26 0.88]
 [0.04 0.09  nan  nan  nan]
 [0.45 0.39 0.72 0.15 0.31]
 [ nan 0.33 0.73 0.43 0.83]]


In [40]:
# 从随机数组中删除包含缺失值的行
print(z,'\n')
print(z[np.sum(np.isnan(z), axis=1) == 0])

[[0.25 0.82 0.08 0.15 0.72]
 [0.62 0.65 0.41 0.26 0.88]
 [0.04 0.09  nan  nan  nan]
 [0.45 0.39 0.72 0.15 0.31]
 [ nan 0.33 0.73 0.43 0.83]] 

[[0.25 0.82 0.08 0.15 0.72]
 [0.62 0.65 0.41 0.26 0.88]
 [0.45 0.39 0.72 0.15 0.31]]


In [38]:
# 统计随机数组中的各元素的数量
z = np.random.randint(0,100,25).reshape((5,5))
print(np.unique(z,return_counts=True))

(array([ 6,  7, 12, 18, 26, 31, 34, 35, 38, 40, 49, 50, 56, 58, 65, 74, 75,
       92]), array([1, 1, 1, 1, 3, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1], dtype=int64))


In [18]:
# 将数组中各元素按指定分类转换为文本值?
z = np.random.randint(1,3,10)
print(z)
label_map = dict(zip((1,2,3),('汽车','公交车','火车')))
print(label_map)
print(np.array([label_map[x] for x in z]).reshape((2,-1)))

[2 2 2 1 1 1 2 1 1 1]
{1: '汽车', 2: '公交车', 3: '火车'}
[['公交车' '公交车' '公交车' '汽车' '汽车']
 ['汽车' '公交车' '汽车' '汽车' '汽车']]


In [23]:
# 将多个 1 维数组拼合为单个 Ndarray
z1 = np.arange(3)
z2 = np.arange(4,7)
z3 = np.arange(7,11)
print(z)
print(np.concatenate([z1,z2,z3]))

[array([0, 1, 2]) array([4, 5, 6]) array([ 7,  8,  9, 10])]
[ 0  1  2  4  5  6  7  8  9 10]


In [25]:
# 打印各元素在数组中升序排列的索引
a = np.random.randint(1,100,20)
print(a.argsort())

[ 9  7  6  3 10 19 11 14 16  4  0 17  2  1  8 12 15  5 13 18]


In [28]:
# 得到二维随机数组各行的最大值
a = np.random.randint(1,20,size=(4,5))
print(a)
print(a.max(axis=1))

[[12 13 14 19  3]
 [ 7 17  1 15  6]
 [ 8  9 10 15 10]
 [17  9 18 15  3]]
[19 17 15 18]


In [30]:
# 得到二维随机数组各行的最小值（区别上面的方法）?
print(np.apply_along_axis(np.min,axis=1,arr=a))

[3 1 8 3]


In [36]:
# 87. 计算两个数组之间的欧氏距离
a = np.array([1,2])
b = np.array([7,8])
# 数学方法
print(np.sqrt(np.power((8-2),2)+np.power((7-1),2)))

# numpy?
print(np.linalg.norm(b-a))

8.48528137423857
8.48528137423857


In [38]:
# 打印复数的实部和虚部
a = np.array([1+2j,3+4j,5+6j])
print("实部:",a.real)
print('虚部',a.imag)

实部: [1. 3. 5.]
虚部 [2. 4. 6.]


In [10]:
# 求解给出矩阵的逆矩阵并验证
matrix = np.array([[1,2],[3,4]])
inv = np.linalg.inv(matrix)

# allclose 
assert np.allclose(np.dot(inv,matrix),np.eye(2))
# np.dot(inv,matrix) == np.eye(2)

In [15]:
# 使用 Z-Score 标准化算法对数据进行标准化处理?
def z_score(x,axis=None):
    min = x.min(axis=axis,keepdims=True)
    max = x.max(axis=axis,keepdims=True)
    result = (x-min)/(max-min)
    return result
z = np.random.randint(10,size=(5,5))
np.set_printoptions(precision=2)
print('Z标准化后','\n',z_score(z))

Z标准化后 
 [[0.33 0.67 1.   0.56 0.89]
 [0.22 0.22 0.22 0.   0.89]
 [0.22 1.   0.78 0.44 1.  ]
 [0.11 0.56 0.33 0.11 1.  ]
 [0.11 0.67 0.22 0.78 0.78]]


In [19]:
# 使用 L2 范数对数据进行标准化处理?
def I2_normalize(v,axis=1,order=2):
    I2 = np.linalg.norm(v,ord=order,axis=axis,keepdims=True)
    I2[I2==0]=1
    return v/I2
z = np.random.randint(10,size=(5,5))
print(z)
print('范数标准化后','\n',I2_normalize(z))

[[4 3 5 0 3]
 [8 3 2 2 9]
 [2 4 5 2 6]
 [8 8 3 9 1]
 [5 9 7 2 2]]
范数标准化后 
 [[0.52 0.39 0.65 0.   0.39]
 [0.63 0.24 0.16 0.16 0.71]
 [0.22 0.43 0.54 0.22 0.65]
 [0.54 0.54 0.2  0.61 0.07]
 [0.39 0.7  0.55 0.16 0.16]]


In [20]:
# 使用 NumPy 计算变量直接的相关性系数?
z = np.array([[1, 2, 1, 9, 10, 3, 2, 6, 7], # 特征 A
             [2, 1, 8, 3, 7, 5, 10, 7, 2], # 特征 B
             [2, 1, 1, 8, 9, 4, 3, 5, 7]]) # 特征 C
print(np.corrcoef(z))

[[ 1.   -0.06  0.97]
 [-0.06  1.   -0.01]
 [ 0.97 -0.01  1.  ]]


In [44]:
# 使用 NumPy 计算矩阵的特征值和特征向量?
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
w,v = np.linalg.eig(m)
# 我们可以通过 P'AP=M 公式反算，验证是否能得到原矩阵。
# v * np.diag(w) * np.linalg.inv(v)
print(m)
print(v)
# print(v*np.diag(w)*np.linalg.inv(v))
print(np.dot(v,np.diag(w),np.linalg.inv(v)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.23 -0.79  0.41]
 [-0.53 -0.09 -0.82]
 [-0.82  0.61  0.41]]
[[-3.74e+00  8.78e-01 -3.98e-16]
 [-8.47e+00  9.69e-02  7.97e-16]
 [-1.32e+01 -6.84e-01 -3.98e-16]]


In [25]:
# 使用 NumPy 计算 Ndarray 两相邻元素差值?
z = np.random.randint(1,10,10)
print(z)
print(np.diff(z,n=1))
print(np.diff(z,n=2))
print(np.diff(z,n=3))

[3 1 3 9 9 4 2 2 7 5]
[-2  2  6  0 -5 -2  0  5 -2]
[ 4  4 -6 -5  3  2  5 -7]
[  0 -10   1   8  -1   3 -12]


In [47]:
# 使用 NumPy 将 Ndarray 相邻元素依次累加
z = np.random.randint(1,10,10)
np.cumsum(z)

array([ 6, 11, 20, 24, 26, 34, 40, 45, 47, 48], dtype=int32)

In [57]:
# 使用 NumPy 按列连接两个数组?
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])
print('按列连接',np.c_[m1,m2])
print('m1:',m1)
print('m2',m2)

按列连接 [[1 4]
 [2 5]
 [3 6]]
m1: [1 2 3]
m2 [4 5 6]


In [56]:
# 使用 NumPy 按行连接两个数组?
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])
np.r_[m1,m2]
print('按行连接',np.r_[m1,m2])
print('m1:',m1)
print('m2',m2)

按行连接 [1 2 3 4 5 6]
m1: [1 2 3]
m2 [4 5 6]


In [58]:
# 构造9*9乘法表
np.fromfunction(lambda x,y: (x+1)*(y+1),(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])